# ──────────────────────────────────────────────────────────
# 2 ▍Prometheus config (ops/prometheus/prometheus.yml)
# ──────────────────────────────────────────────────────────
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'intent_parser_local'
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/targets.json
