# ──────────────────────────────────────────────────────────
# 1 ▍docker‑compose (root/docker‑compose.yml)
# ──────────────────────────────────────────────────────────
version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./ops/prometheus/file_sd/:/etc/prometheus/file_sd/:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - ./ops/grafana/provisioning/:/etc/grafana/provisioning/:ro
      - ./ops/grafana/dashboards/:/var/lib/grafana/dashboards/:ro
    depends_on:
      - prometheus
    restart: unless-stopped
